version: "3.9"

services:
  db:
    container_name: leading_db
    image: postgres:15
    volumes:
      - ./db/logs:/var/log
      - default-data:/var/lib/postgresql/data
      - leading-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    command: postgres -c logging_collector=on -c log_directory=/var/log -c log_filename=postgresql.log -c log_statement=all
    ports:
      - 5432:5432

  api:
    build: ./api
    container_name: leading_api
    volumes:
      - ./api:/code
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: ["bash", "-c", "python manage.py runserver 0.0.0.0:8000"]
    ports:
      - 8000:8000
    tty: true

  localstack:
    container_name: leading_localstack
    image: localstack/localstack:latest
    environment:
      SERVICES: sqs
      DEFAULT_REGION: us-east-1
      DOCKER_HOST: tcp://docker-compose-localstack:2375
    ports:
      - 4566:4566

volumes:
  default-data:
  leading-db-data:
  leading-localstack-data:
